build:
  image: bjodah/bjodahimg16dev:latest
  commands:
    - bash -c '[[ $(python setup.py --version) =~ ^[0-9]+.* ]]'
    - ./scripts/ci.sh finitediff
    - ./scripts/generate_docs.sh
    - PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe
    - ./scripts/prepare_deploy.sh
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: finitediff
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false

