build:
  image: bjodah/bjodahimg18dev:v1.0
  environment:
    - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-6.0/bin/llvm-symbolizer
    - ASAN_OPTIONS=symbolize=1
  commands:
    - bash -c '[[ $(python3 setup.py --version) =~ ^[0-9]+.* ]]'
    - (cd examples/; make -B CXX=clang++-6.0 EXTRA_COMPILE_ARGS="-fsanitize=address -O0 -g")
    - (cd examples/; make -B CXX=g++ EXTRA_COMPILE_ARGS="-DNDEBUG -O2")
    - (cd tests/; make -B CXX=clang++-6.0 EXTRA_COMPILE_ARGS="-fsanitize=address -O0 -g")
    - (cd tests/; make -B CXX=g++ EXTRA_COMPILE_ARGS="-DNDEBUG -O2")
    - ./scripts/ci.sh finitediff
    - ./scripts/generate_docs.sh
    - PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe
    - ./scripts/prepare_deploy.sh
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: finitediff
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false

