build:
  image: bjodah/bjodahimg:v1.1
  commands:
    - ./scripts/ci.sh finitediff
    - ./scripts/generate_docs.sh
    - ./scripts/prepare_deploy.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: finitediff
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false

