language: python
python:
  - "2.7"
before_install:
  - pip install -r requirements.txt
  - sudo apt-get install -qq gfortran g++
install:
  - python setup.py build_ext --inplace
  - export PYTHONPATH=.:$PYTHONPATH
# command to run tests
script: 
  - PYTHONPATH=$(pwd) py.test
  - USE_FORTRAN=1 python setup.py build_ext --inplace
  - rm finitediff/*templated*.so
  - PYTHONPATH=$(pwd) py.test
notifications:
  email: false
