sudo: required
dist: trusty
language: generic
before_install:
  - sudo apt-get install -qq gfortran g++ cython python-pip python-numpy python-argh python-pytest
install:
  - python setup.py build_ext --inplace
  - export PYTHONPATH=.:$PYTHONPATH
# command to run tests
script: 
  - PYTHONPATH=$(pwd) py.test
  - USE_FORTRAN=1 python setup.py build_ext --inplace
  - rm finitediff/*templated*.so
  - PYTHONPATH=$(pwd) py.test
notifications:
  email: false
