language: python
python:
  - "2.7"
#later: - "3.3"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "sudo apt-get install -qq gfortran"
# command to run tests
script: py.test
