sudo: required
dist: trusty
language: generic
before_install:
  - sudo apt-get install -qq gfortran g++ python-pip python-numpy python-argh python-pytest python-pip python-dev
  - python -m pip install --user pycompilation
  - python -m pip install --user Cython --install-option="--no-cython-compile"
install:
  - python setup.py build_ext --inplace
  - export PYTHONPATH=.:$PYTHONPATH
# command to run tests
script: 
  - PYTHONPATH=$(pwd) python -m pytest
  - FINITEDIFF_USE_FORTRAN=1 python setup.py build_ext --inplace
  - rm finitediff/*templated*.so
  - PYTHONPATH=$(pwd) py.test
notifications:
  email: false
