package:
  name: finitediff
  version: 0.3.0.git

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - cython
  run:
    - numpy
    - python

test:
  requires:
    - numpy

about:
  home: https://github.com/bjodah/finitediff
  license: Simplified BSD license
