{% set name = "finitediff" %}
{% set version = "0.4.0.dev0+git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - cython
  run:
    - numpy
    - python

test:
  requires:
    - numpy

about:
  home: https://github.com/bjodah/finitediff
  license: BSD 2-Clause
  license_file: LICENSE
