{% set name = "finitediff" %}
{% set version = "0.6.0.dev0+git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - setuptools
    - numpy 1.14.*
  run:
    - python
    - numpy >=1.14
    - scipy

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs {{ name }}

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
